on:
  push:
    branches:
    - main
  pull_request:

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    environment: production
    
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t myimage .
    
